apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: scenario-file
  namespace: kube-system
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - kube-system
    labelSelectors:
      "k8s-app": "kube-dns"
  delay:
    latency: '10ms'
    correlation: '100'
    jitter: '0ms'